osx_image: xcode9.2
language: objective-c
cache: cocoapods
before_install: gem install xcpretty cocoapods obcd slather -N
script: xcodebuild -project Demo.xcodeproj -scheme Demo -sdk iphonesimulator build test -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test | xcpretty -c && exit ${PIPESTATUS[0]}
after_success: slather